export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';

export const DEL_POST = 'DEL_POST';
export const ADD_POST = 'ADD_POST';
export const EDIT_POST = 'EDIT_POST';